[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=63.0.0", "wheel"]

[tool.black]
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
^/tmp
'''
include = '\.pyi?$'
target-version = ['py38', 'py39', 'py310', 'py311']

[tool.ruff.lint.isort]
section-order = ["future", "patch", "standard-library", "third-party", "first-party", "local-folder"]
sections = { "patch" = ["datahub.utilities._markupsafe_compat", "datahub.sql_parsing._sqlglot_patch"] }
combine-as-imports = true

[tool.ruff]
target-version = "py38"
# Same as Black.
line-length = 88
# Exclude directories matching these patterns.
exclude = [
    ".git",
    "src/datahub/metadata",
    "venv",
    ".tox",
    "__pycache__",
]

[tool.ruff.lint]
extend-select = [
    "B",  # Bugbear
    "C90",
    "E",
    "F",
    "G010",  # logging.warn -> logging.warning
    "I",  # Import sorting
    "TID",  # Tidy imports
]
extend-ignore = [
    # Ignore line length violations (handled by Black)
    "E501",
    # Ignore whitespace before ':' (matches Black)
    "E203",
    # Allow usages of functools.lru_cache
    "B019",
    # Allow function call in argument defaults
    "B008",
    # TODO: Enable these later
    "B006",  # Mutable args
    "B017",  # Do not assert blind exception
    "B904",  # Checks for raise statements in exception handlers that lack a from clause
]

[tool.ruff.lint.mccabe]
max-complexity = 20

[tool.ruff.lint.flake8-tidy-imports]
ban-relative-imports = "all"

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]