[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=63.0.0", "wheel"]

[tool.black]
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
^/tmp
'''
include = '\.pyi?$'
target-version = ['py38', 'py39', 'py310', 'py311']


[tool.ruff.lint.isort]
combine-as-imports = true
known-first-party = ["datahub"]
extra-standard-library = ["__future__", "datahub.utilities._markupsafe_compat", "datahub.sql_parsing._sqlglot_patch"]
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]
force-sort-within-sections = false
force-wrap-aliases = false
split-on-trailing-comma = false
order-by-type = true
relative-imports-order = "closest-to-furthest"
force-single-line = false
single-line-exclusions = ["typing"]
length-sort = false
from-first = false
required-imports = []
classes = ["typing"]

[tool.ruff]
# Same as Black.
line-length = 88
# Exclude directories matching these patterns.
exclude = [
    ".git",
    "src/datahub/metadata",
    "venv",
    ".tox",
    "__pycache__",
]

[tool.ruff.lint]
select = [
    "B",
    "C90",
    "E",
    "F",
    "I", # For isort
    "TID",
]
ignore = [
    # Ignore line length violations (handled by Black)
    "E501",
    # Ignore whitespace before ':' (matches Black)
    "E203",
    # Allow usages of functools.lru_cache
    "B019",
    # Allow function call in argument defaults
    "B008",
    # TODO: Enable these later
    "B006",  # Mutable args
    "B017",  # Do not assert blind exception
    "B904",  # Checks for raise statements in exception handlers that lack a from clause
]

[tool.ruff.lint.mccabe]
max-complexity = 20

[tool.ruff.lint.flake8-tidy-imports]
# Disallow all relative imports.
ban-relative-imports = "all"


[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]